version: '2'
services:
    websurvey-app:
        image: websurvey
        external_links:
            - websurvey-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=WebSurvey
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    websurvey-mongodb:
        extends:
            file: mongodb.yml
            service: websurvey-mongodb
