version: '2'
services:
    websurvey-mongodb:
        container_name: websurvey-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb websurvey-mongodb-config
    websurvey-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    websurvey-mongodb-config:
        image: mongo:3.2.10
        container_name: websurvey-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
